import * as T from 'three';import {OrbitControls} from 'orbit';import {createPlant,SPECIES,disposePlant} from './flora.js?v=20261008-1';import {Terrain,WIDTH,DEPTH,CENTER_X,CENTER_Z,X0,X1,Z0,Z1,RES,heightAt,SOILS} from './terrain.js?v=20261007-2';
import {PROPS,createProp,animateWater,animateProps} from './props.js?v=20261008-3';import {GestureIntent} from './gestures.js?v=20261007-2';
import {allModules,getModule,instance,loadModules,prepare,register,hideModule,ensureRefs,metadata,modulePackage,fromPackage,releaseInstance,CATEGORIES} from './modules.js?v=20261007-2';
Object.assign(SPECIES,PROPS);
function syncModuleSpecies(){for(const item of allModules())SPECIES[item.id]={name:item.name,note:item.missing?'Archivo pendiente':CATEGORIES[item.category],height:item.height,category:'modules'}}
const moduleWarnings=await loadModules();syncModuleSpecies();

const createItem=(type,seed)=>type.startsWith('mod:')?instance(getModule(type)):PROPS[type]?createProp(type,seed):createPlant(type,seed);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)],vp=$('#viewport');
let renderer;try{renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true})}catch(e){$('#loading').textContent='Esta muestra requiere WebGL. Ábrela en un navegador con aceleración gráfica.';throw e}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;vp.prepend(renderer.domElement);renderer.domElement.setAttribute('aria-label','Terreno 3D editable');
const scene=new T.Scene();scene.background=new T.Color('#cdd9c5');scene.fog=new T.Fog('#cdd9c5',1100,2300);const camera=new T.PerspectiveCamera(39,1,.5,4000);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.maxPolarAngle=Math.PI*.485;controls.minDistance=8;controls.maxDistance=1800;controls.target.set(CENTER_X,35,CENTER_Z);
function home(){camera.position.set(CENTER_X+610,560,CENTER_Z+690);controls.target.set(CENTER_X,35,CENTER_Z);controls.update()}home();scene.add(new T.HemisphereLight('#fff8df','#68734d',2.1));const sun=new T.DirectionalLight('#fff3d3',3.2);sun.position.set(CENTER_X-350,650,CENTER_Z+250);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-650,right:650,top:650,bottom:-650,near:1,far:1800});sun.shadow.bias=-.0008;sun.shadow.normalBias=.55;sun.shadow.radius=3;scene.add(sun);
const terrain=new Terrain();scene.add(terrain.mesh);
function terrainSkirt(){const bottom=-24,positions=[];function edge(points){for(let i=1;i<points.length;i++){const [ax,az]=points[i-1],[bx,bz]=points[i],ay=heightAt(ax,az),by=heightAt(bx,bz);positions.push(ax,ay,az,ax,bottom,az,bx,by,bz,bx,by,bz,ax,bottom,az,bx,bottom,bz)}}const nx=69,nz=63,top=[],right=[],bottomEdge=[],left=[];for(let i=0;i<=nx;i++)top.push([X0+(X1-X0)*i/nx,Z0]);for(let i=0;i<=nz;i++)right.push([X1,Z0+(Z1-Z0)*i/nz]);for(let i=nx;i>=0;i--)bottomEdge.push([X0+(X1-X0)*i/nx,Z1]);for(let i=nz;i>=0;i--)left.push([X0,Z0+(Z1-Z0)*i/nz]);edge(top);edge(right);edge(bottomEdge);edge(left);const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(positions,3));g.computeVertexNormals();const m=new T.MeshStandardMaterial({color:'#75664a',roughness:1,side:T.DoubleSide});const skirt=new T.Mesh(g,m);skirt.receiveShadow=true;skirt.name='Paredes del terreno';return skirt}scene.add(terrainSkirt());
const PROPERTY_BOUNDARY=[[183.6,200.1],[203.6,207.3],[224,189.4],[222.4,177.7],[242.9,167.3],[280.1,71.5],[317.1,2.1],[371.3,-90],[376.4,-124.3],[351,-166.4],[314,-167.2],[277.8,-142.1],[242.1,-203.1],[218.5,-232.2],[-3.1,-389.5],[-121.2,-292.6],[-58.4,-261.6],[68.7,-207.6],[36.3,-55.9],[14.5,-49.1],[-23.9,-53.3],[-132.2,-85.2],[-142.5,-26.2],[-180.9,-38.9],[-237.5,-68.6],[-276.7,-104.1],[-311.2,-140.6],[-339.9,-160.9],[-349.3,-41.2],[-284.8,16],[-303.7,32.9],[-290,51],[-274.6,35.5],[-229.9,70.7],[-167.3,86.4],[-120.9,86.5],[-118.8,114.9],[-99.9,121.3],[-84.7,98.9],[-21.1,156.5],[-38.3,176.3],[-18.5,197.3],[-2.7,180],[8.3,190.2],[95.9,270.7]];
const boundaryGeometry=new T.BufferGeometry().setFromPoints(PROPERTY_BOUNDARY.map(([x,z])=>new T.Vector3(x,heightAt(x,z)+1,z)));
const boundaryLine=new T.LineLoop(boundaryGeometry,new T.LineBasicMaterial({color:0xf2c84b,transparent:true,opacity:.95,depthTest:true}));boundaryLine.name='Límite del predio';boundaryLine.renderOrder=4;scene.add(boundaryLine);
const objects=new T.Group();scene.add(objects);let selected=null,mode='orbit',activeType='majagua',activeSoil=2,radius=.35,blend=.55,showLabels=true,nextId=1;const labels=new Map(),history=[],future=[];let autosaveBlocked=false,editBefore=null;let saveTimer,toastTimer,dirty=false,pendingSave=Promise.resolve();
const boxHelper=new T.BoxHelper(new T.Object3D(),0xa1bc72);boxHelper.visible=false;boxHelper.material.depthTest=false;boxHelper.renderOrder=10;scene.add(boxHelper);const axes=new T.AxesHelper(2);axes.visible=false;axes.material.depthTest=false;axes.renderOrder=11;scene.add(axes);
const ring=new T.LineLoop(new T.BufferGeometry(),new T.LineBasicMaterial({color:'#f4eccc',depthTest:false}));ring.visible=false;ring.renderOrder=12;scene.add(ring);
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3000)}
function setMode(m){mode=m;controls.enabled=true;controls.mouseButtons.LEFT=m==='orbit'?T.MOUSE.ROTATE:null;controls.touches.ONE=m==='orbit'?T.TOUCH.ROTATE:null;controls.touches.TWO=T.TOUCH.DOLLY_PAN;controls.screenSpacePanning=true;controls.rotateSpeed=.7;controls.zoomSpeed=.8;controls.panSpeed=.85;$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));ring.visible=false;renderer.domElement.style.cursor=m==='orbit'?'grab':m==='paint'?'crosshair':m==='place'?'copy':'default';const hints={orbit:'1 dedo gira · 2 dedos desplazan · pellizca para acercar · toca para seleccionar',select:'Toca un objeto para seleccionarlo · dos dedos para navegar',move:'1 dedo mueve X/Z · altura Y en el panel · 2 dedos navegan',paint:'1 dedo pinta · 2 dedos navegan sin pintar · Ctrl+Z deshace',place:'Toca para colocar '+SPECIES[activeType].name+' · 2 dedos para navegar'};$('#modeHint').textContent=hints[m]}
function record(o){return {id:o.userData.id,type:o.userData.type,seed:o.userData.seed,position:o.position.toArray(),rotation:[o.rotation.x,o.rotation.y,o.rotation.z],scale:o.scale.x}}
function state(copy=true){return {version:3,catalogRefs:allModules().filter(m=>objects.children.some(o=>o.userData.type===m.id)).map(metadata),objects:objects.children.map(record),a:copy?terrain.a.slice():terrain.a,b:copy?terrain.b.slice():terrain.b,c:copy?terrain.c.slice():terrain.c,radius,blend,camera:camera.position.toArray(),target:controls.target.toArray(),nextId}}
function checkpoint(){history.push(state());if(history.length>10)history.shift();future.length=0;updateHistory()}
function updateHistory(){$('#undo').disabled=!history.length;$('#redo').disabled=!future.length}
function addObject(type,x,z,seed,id){if(!SPECIES[type]){ensureRefs([{id:type,name:'Módulo pendiente',height:1,category:'decor',yaw:0}]);syncModuleSpecies()}let o=createItem(type,seed);o.userData={type,seed,id:id??nextId++};o.position.set(x,heightAt(x,z),z);o.rotation.y=(seed%628)/100;objects.add(o);const label=document.createElement('div');label.className='label';label.textContent=SPECIES[type].name;$('#labels').append(label);labels.set(o,label);return o}
function removeObject(o){labels.get(o)?.remove();labels.delete(o);objects.remove(o);if(o.userData.type?.startsWith('mod:'))releaseInstance(o);else disposePlant(o)}
function list(){const el=$('#objectList');el.replaceChildren();for(const o of objects.children){let b=document.createElement('button');b.textContent=SPECIES[o.userData.type].name;let n=document.createElement('small');n.textContent=String(o.userData.id).padStart(2,'0');b.append(n);b.classList.toggle('active',o===selected);b.onclick=()=>{select(o);setMode('select')};el.append(b)}$('#count').textContent=objects.children.length}
function select(o){selected=o;boxHelper.visible=axes.visible=!!o;if(o){boxHelper.setFromObject(o);axes.position.copy(o.position);$('#selectedName').textContent=SPECIES[o.userData.type].name+' · '+String(o.userData.id).padStart(2,'0')}else $('#selectedName').textContent='Selecciona un objeto del terreno';$('#transform').querySelectorAll('input,button').forEach(e=>e.disabled=!o);syncFields();list();if($('#mobileObject'))$('#mobileObject').textContent=o?'Objeto · '+SPECIES[o.userData.type].name:'Objeto'}
function syncFields(){const o=selected;for(const [i,axis] of ['X','Y','Z'].entries()){$('#pos'+axis).value=o?o.position.getComponent(i).toFixed(2):'';$('#rot'+axis).value=o?T.MathUtils.radToDeg(o.rotation[['x','y','z'][i]]).toFixed(1):''}$('#rotation360').value=o?(T.MathUtils.radToDeg(o.rotation.y)%360+360)%360:0;$('#rotationOut').textContent=Math.round(+$('#rotation360').value)+'°';$('#scale').value=o?o.scale.x:1;$('#scaleOut').textContent=(o?o.scale.x:1).toFixed(2).replace('.',',')+'×';if(o){boxHelper.setFromObject(o);axes.position.copy(o.position)}}
function saveStatus(kind){const e=$('#saveLight');if(e){e.dataset.state=kind;e.title=kind==='saving'?'Guardando…':kind==='saved'?'Guardado correctamente':'Cambios pendientes'}}
function changed(sync=true){dirty=true;saveStatus('dirty');clearTimeout(saveTimer);saveTimer=setTimeout(()=>save(false),1100);if(sync)syncFields()}
function restore(s){ensureRefs(s.catalogRefs||[]);syncModuleSpecies();select(null);for(const o of [...objects.children])removeObject(o);for(const r of s.objects){let o=addObject(r.type,0,0,r.seed,r.id);o.position.fromArray(r.position);o.rotation.set(...r.rotation);o.scale.setScalar(r.scale)}terrain.a.set(s.a);terrain.b.set(s.b);terrain.c.set(s.c||new Uint8Array(RES*RES*4));terrain.dirty();radius=s.radius;blend=s.blend;nextId=s.nextId;$('#radius').value=radius;$('#blend').value=Math.round(blend*100);updateBrush();if(s.camera)camera.position.fromArray(s.camera);if(s.target)controls.target.fromArray(s.target);controls.update();list()}
function undo(){if(!history.length)return;future.push(state());restore(history.pop());changed();updateHistory();toast('Último cambio deshecho')}
function redo(){if(!future.length)return;history.push(state());restore(future.pop());changed();updateHistory();toast('Cambio restaurado')}
const DB='media-luna-paisaje-inegi-v1';
function database(){return new Promise((resolve,reject)=>{const request=indexedDB.open(DB,1);request.onupgradeneeded=()=>request.result.createObjectStore('project');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function saveLocal(snapshot){const db=await database();await new Promise((resolve,reject)=>{const tx=db.transaction('project','readwrite');tx.objectStore('project').put(snapshot,'current');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close()}
function portable(snapshot){const s={...snapshot};s.a=bytes64(s.a);s.b=bytes64(s.b);s.c=bytes64(s.c);s.modules=s.catalogRefs.map(r=>getModule(r.id)).filter(m=>m?.buffer).map(modulePackage);return s}
async function saveShared(snapshot){let token='';try{token=sessionStorage.getItem('medialuna_admin_token')||''}catch{}if(!token){token=(prompt('Clave de administrador para publicar este avance y verlo en todos tus dispositivos:')||'').trim();if(!token)throw Error('PUBLICACIÓN_CANCELADA');try{sessionStorage.setItem('medialuna_admin_token',token)}catch{}}const body=new FormData();body.append('payload',new Blob([JSON.stringify(portable(snapshot))],{type:'application/json'}),'proyecto.json');const response=await fetch('./api/save.php',{method:'POST',headers:{'X-Admin-Token':token},body});const result=await response.json().catch(()=>({}));if(!response.ok){if(response.status===401)try{sessionStorage.removeItem('medialuna_admin_token')}catch{}throw Error(result.error||'No se pudo publicar en el servidor')}return result}
function save(explicit=true){if(autosaveBlocked){if(explicit)toast('Guardado protegido: exporta tu trabajo para conservarlo.');return Promise.resolve()}if(editBefore)return Promise.resolve();const snapshot=state();saveStatus('saving');pendingSave=pendingSave.catch(()=>{}).then(async()=>{await saveLocal(snapshot);if(explicit)await saveShared(snapshot);dirty=false;saveStatus('saved');if(explicit)toast('Avance publicado · ya está disponible en tus otros dispositivos')}).catch(e=>{dirty=true;saveStatus('dirty');if(explicit&&e.message!=='PUBLICACIÓN_CANCELADA')toast('No se pudo publicar: '+e.message);else if(explicit)toast('El avance quedó guardado sólo en este dispositivo')});return pendingSave}
async function loadShared(){const response=await fetch('./api/save.php',{cache:'no-store'});if(response.status===404)return null;if(!response.ok)throw Error('Servidor '+response.status);const s=await response.json();for(const key of ['a','b','c'])if(typeof s[key]==='string')s[key]=from64(s[key]);ensureRefs(s.catalogRefs||[]);syncModuleSpecies();return validState(s)?s:null}
async function load(){try{const shared=await loadShared();if(shared){restore(shared);await saveLocal(shared);toast('Avance compartido recuperado del servidor');return true}}catch(e){console.warn('No se pudo leer el avance compartido',e)}try{const db=await database(),s=await new Promise((resolve,reject)=>{const q=db.transaction('project').objectStore('project').get('current');q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)});if(s){ensureRefs(s.catalogRefs||[]);syncModuleSpecies()}if(s&&validState(s)){await new Promise((resolve,reject)=>{const tx=db.transaction('project','readwrite'),store=tx.objectStore('project'),q=store.get('backup-before-update-02');q.onsuccess=()=>{if(!q.result)store.put(s,'backup-before-update-02')};tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close();restore(s);toast('Avance local recuperado · publícalo para verlo en otros dispositivos');return true}db.close();if(s){autosaveBlocked=true;toast('Tu avance requiere revisión. No se sobrescribirá.');return false}}catch(e){autosaveBlocked=true;console.warn('Guardado local no disponible',e);toast('No se pudo recuperar el guardado; exporta una copia antes de continuar.')}return false}
function validState(s){return s&&[2,3].includes(s.version)&&s.a?.length===RES*RES*4&&s.b?.length===RES*RES*4&&(s.version===2||s.c?.length===RES*RES*4)&&Array.isArray(s.objects)&&s.objects.every(o=>(SPECIES[o.type]||/^mod:[a-z0-9_-]{1,80}$/.test(o.type))&&Number.isFinite(o.seed)&&Number.isInteger(o.id)&&[o.position,o.rotation].every(v=>Array.isArray(v)&&v.length===3&&v.every(Number.isFinite))&&o.scale>=.2&&o.scale<=3)&&Number.isFinite(s.radius)&&s.radius>=.1&&s.radius<=6&&Number.isFinite(s.blend)&&s.blend>=.05&&s.blend<=.85&&Number.isInteger(s.nextId)&&s.nextId>Math.max(0,...s.objects.map(o=>o.id))&&[s.camera,s.target].every(v=>Array.isArray(v)&&v.length===3&&v.every(Number.isFinite))}
function bytes64(a){let chunks=[];for(let i=0;i<a.length;i+=32768)chunks.push(String.fromCharCode(...a.subarray(i,i+32768)));return btoa(chunks.join(''))}
function from64(s){let raw=atob(s),a=new Uint8Array(raw.length);for(let i=0;i<a.length;i++)a[i]=raw.charCodeAt(i);return a}
function downloadJSON(value,name){const blob=new Blob([JSON.stringify(value)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}
$('#export').onclick=()=>{try{let s=state(false);s.a=bytes64(s.a);s.b=bytes64(s.b);s.c=bytes64(s.c);s.modules=s.catalogRefs.map(r=>getModule(r.id)).filter(m=>m?.buffer).map(modulePackage);downloadJSON(s,'MediaLuna-paisaje-avance.json');toast('Avance exportado con módulos, pintura y objetos')}catch(e){toast('No se pudo exportar: '+e.message)}};
$('#import').onclick=()=>$('#file').click();$('#file').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>500*1024*1024)throw Error('El avance supera 500 MB');const s=JSON.parse(await f.text());s.a=from64(s.a);s.b=from64(s.b);if(s.c)s.c=from64(s.c);if(!validState(s))throw Error('Avance incompatible');if(s.modules&&!Array.isArray(s.modules))throw Error('Módulos inválidos');const staged=[];for(const raw of s.modules||[]){if(!getModule(raw.id)?.template)staged.push(await fromPackage(raw))}for(const item of staged)await register(item);ensureRefs(s.catalogRefs||[]);syncModuleSpecies();checkpoint();restore(s);renderModules();changed();toast('Avance importado')}catch(e){toast('No se pudo importar: '+e.message)}finally{e.target.value=''}};
// True 3D thumbnails rendered from the same catalog models.
function thumbnail(type){const s=new T.Scene();s.background=new T.Color('#e9eddc');s.add(new T.HemisphereLight('#ffffeb','#777957',2.5));let l=new T.DirectionalLight('#fff4dc',3);l.position.set(-4,8,5);s.add(l);let o=createItem(type,42);s.add(o);const b=new T.Box3().setFromObject(o),c=b.getCenter(new T.Vector3()),size=b.getSize(new T.Vector3()),extent=Math.max(size.x,size.y,size.z)*.68;const cam=new T.OrthographicCamera(-extent,extent,extent, -extent,.01,100);cam.position.copy(c).add(new T.Vector3(5,3.5,7));cam.lookAt(c);let target=new T.WebGLRenderTarget(160,160);const old=renderer.getRenderTarget();renderer.setRenderTarget(target);renderer.render(s,cam);let pixels=new Uint8Array(160*160*4);renderer.readRenderTargetPixels(target,0,0,160,160,pixels);renderer.setRenderTarget(old);let can=document.createElement('canvas');can.width=can.height=160;let ctx=can.getContext('2d'),im=ctx.createImageData(160,160);for(let y=0;y<160;y++)im.data.set(pixels.subarray((159-y)*640,(160-y)*640),y*640);ctx.putImageData(im,0,0);target.dispose();if(type.startsWith('mod:'))releaseInstance(o);else disposePlant(o);return can.toDataURL()}
function card(container,name,note,url,fn){let b=document.createElement('button');b.className='card';b.innerHTML='<img alt=""><strong></strong><small></small>';b.querySelector('img').src=url;b.querySelector('strong').textContent=name;b.querySelector('small').textContent=note;b.setAttribute('aria-label',name);b.onclick=()=>{container.querySelectorAll('.card').forEach(c=>c.classList.remove('active'));b.classList.add('active');fn()};container.append(b);return b}
const moduleTabButton=$('[data-tab="modules"]');moduleTabButton.insertAdjacentHTML('beforebegin','<button data-tab="decorations">Decoraciones</button><button data-tab="playground">Juegos infantiles</button>');$('#modules').insertAdjacentHTML('beforebegin','<div id="decorations" class="tab" hidden><div class="hint">Objetos rurales para ambientar caminos, jardines y áreas de convivencia.</div><div class="cards" id="decorationsCards"></div><div class="subtle">Cada pieza se puede mover, girar, escalar y duplicar.</div></div><div id="playground" class="tab" hidden><div class="hint">Juegos infantiles a escala para formar áreas recreativas.</div><div class="cards" id="playgroundCards"></div></div>');
for(const [type,info] of Object.entries(SPECIES)){if(type.startsWith('mod:'))continue;let container=$(info.category?'#'+info.category+'Cards':type.startsWith('piedra')?'#rockCards':'#plantCards');card(container,info.name,info.note,thumbnail(type),()=>{activeType=type;setMode('place');closeDrawers()})}
SOILS.forEach((s,i)=>{let b=card($('#groundCards'),s.name,s.note,terrain.textures[i].canvas.toDataURL(),()=>{activeSoil=i;$('#erase').classList.remove('active');setMode('paint')});if(i===2)b.classList.add('active')});
function updateBrush(){radius=+$('#radius').value;blend=+$('#blend').value/100;$('#radiusOut').textContent=radius.toFixed(2).replace('.',',')+' m';$('#blendOut').textContent=Math.round(blend*100)+' %'}$('#radius').oninput=updateBrush;$('#blend').oninput=updateBrush;for(let id of ['radius','blend'])$('#'+id).onchange=()=>changed();$$('[data-radius]').forEach(b=>b.onclick=()=>{$('#radius').value=b.dataset.radius;updateBrush();changed()});$('#erase').onclick=()=>{activeSoil=-1;$('#groundCards').querySelectorAll('.card').forEach(b=>b.classList.remove('active'));$('#erase').classList.add('active');setMode('paint')};
$$('[data-tab]').forEach(b=>b.onclick=()=>{$$('[data-tab]').forEach(n=>n.classList.toggle('active',n===b));$$('.tab').forEach(t=>t.hidden=t.id!==b.dataset.tab);if(b.dataset.tab==='ground')setMode('paint');else setMode('select')});$$('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('#home').onclick=home;$('#top').onclick=()=>{camera.position.set(CENTER_X,980,CENTER_Z+.01);controls.target.set(CENTER_X,25,CENTER_Z);controls.update()};$('#boundaryBtn').onclick=()=>{boundaryLine.visible=!boundaryLine.visible;$('#boundaryBtn').textContent='Límite '+(boundaryLine.visible?'✓':'');$('#boundaryBtn').setAttribute('aria-pressed',String(boundaryLine.visible))};$('#labelsBtn').onclick=()=>{showLabels=!showLabels;$('#labelsBtn').textContent='Nombres '+(showLabels?'✓':'');$('#labels').hidden=!showLabels};$('#save').onclick=()=>save();$('#undo').onclick=undo;$('#redo').onclick=redo;
const positionControl=$('#posX').closest('.control');positionControl.insertAdjacentHTML('beforeend','<div class="nudge-pad" aria-label="Mover por pasos"><button data-nudge="z:-0.25">↑<small>adelante</small></button><button data-nudge="y:0.25">＋Y<small>subir</small></button><button data-nudge="x:-0.25">←<small>izquierda</small></button><button data-nudge="x:0.25">→<small>derecha</small></button><button data-nudge="z:0.25">↓<small>atrás</small></button><button data-nudge="y:-0.25">−Y<small>bajar</small></button></div>');
const rotationControl=$('#rotX').closest('.control');rotationControl.querySelector('.xyz').insertAdjacentHTML('afterend','<label class="rotation-slider">Giro horizontal <output id="rotationOut">0°</output><input id="rotation360" type="range" min="0" max="360" step="1" value="0"></label>');
const objectHeading=$('.object-heading');objectHeading.id='toggleObjects';objectHeading.setAttribute('role','button');objectHeading.setAttribute('tabindex','0');objectHeading.setAttribute('aria-expanded','false');$('#objectList').hidden=true;
for(const [i,axis] of ['X','Y','Z'].entries())for(const kind of ['pos','rot']){const field=$('#'+kind+axis);let started=false;field.onfocus=()=>started=false;field.oninput=e=>{if(!selected||e.target.value==='')return;const value=Number(e.target.value);if(!Number.isFinite(value)||Math.abs(value)>10000)return;if(!started){checkpoint();started=true}if(kind==='pos')selected.position.setComponent(i,value);else selected.rotation[['x','y','z'][i]]=T.MathUtils.degToRad(value);changed(false)};field.onblur=()=>{started=false;syncFields()};field.onkeydown=e=>{if(e.key==='Enter')field.blur()}};
$('#rotation360').onpointerdown=()=>{if(selected)checkpoint()};$('#rotation360').oninput=e=>{if(selected){selected.rotation.y=T.MathUtils.degToRad(+e.target.value);$('#rotationOut').textContent=Math.round(+e.target.value)+'°';changed(false)}};
$$('[data-nudge]').forEach(b=>b.onclick=()=>{if(!selected)return;checkpoint();const [axis,amount]=b.dataset.nudge.split(':');selected.position[axis]+=Number(amount);changed()});
$('#toggleObjects').onclick=()=>{const hidden=$('#objectList').hidden=!$('#objectList').hidden;$('#toggleObjects').setAttribute('aria-expanded',String(!hidden));$('#toggleObjects').classList.toggle('collapsed',hidden)};
$('#scale').onpointerdown=()=>{if(selected)checkpoint()};$('#scale').onkeydown=e=>{if(selected&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End'].includes(e.key))checkpoint()};$('#scale').oninput=e=>{if(selected){selected.scale.setScalar(+e.target.value);changed()}};$('#snap').onclick=()=>{if(selected){checkpoint();selected.position.y=heightAt(selected.position.x,selected.position.z);changed()}};for(const [id,angle] of [['turnLeft',-15],['turnRight',15]])$('#'+id).onclick=()=>{if(selected){checkpoint();selected.rotation.y+=T.MathUtils.degToRad(angle);changed()}};$('#duplicate').onclick=()=>{if(!selected)return;checkpoint();let o=selected,n=addObject(o.userData.type,o.position.x+1,o.position.z+1,o.userData.seed);n.rotation.copy(o.rotation);n.scale.copy(o.scale);n.position.y=o.position.y;select(n);changed()};$('#delete').onclick=()=>{if(selected){checkpoint();removeObject(selected);select(null);changed()}};
const ray=new T.Raycaster(),mouse=new T.Vector2();let down=false,lastPoint=null,moveOffset=null,pointerId=null;
function hit(e,target=terrain.mesh){const r=renderer.domElement.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(mouse,camera);return target===objects?ray.intersectObjects(objects.children,true)[0]:ray.intersectObject(target)[0]}
function owner(hit){if(!hit)return null;let o=hit.object;while(o&&o.parent!==objects)o=o.parent;return o?.parent===objects?o:null}
function brushAt(p){const pts=[];for(let i=0;i<64;i++){const a=i/64*Math.PI*2,x=p.x+radius*Math.cos(a),z=p.z+radius*Math.sin(a);pts.push(new T.Vector3(x,heightAt(x,z)+.05,z))}ring.geometry.dispose();ring.geometry=new T.BufferGeometry().setFromPoints(pts);ring.visible=true}
function strokeTo(p){if(lastPoint){let dist=lastPoint.distanceTo(p),steps=Math.max(1,Math.ceil(dist/Math.max(.025,radius*.25)));for(let i=1;i<=steps;i++){let q=lastPoint.clone().lerp(p,i/steps);terrain.paint(q.x,q.z,radius,blend,activeSoil)}}else terrain.paint(p.x,p.z,radius,blend,activeSoil);lastPoint=p.clone()}
const intent=new GestureIntent();let startEvent=null,editObject=null,originalPosition=null,editKind=null;
function beginEdit(e){const ground=hit(e);if(!ground)return;clearTimeout(saveTimer);editKind=mode;
 if(mode==='paint'){editBefore=state();terrain.start();lastPoint=null;down=true;strokeTo(ground.point)}
 else if(mode==='move'){const o=owner(hit(e,objects));select(o);if(o){editBefore=state();editObject=o;originalPosition=o.position.clone();moveOffset=o.position.clone().sub(ground.point);down=true}}
}
function finishEdit(cancel=false){if(!editBefore)return;const before=editBefore;editBefore=null;
 if(cancel){if(editKind==='paint'){terrain.a.set(before.a);terrain.b.set(before.b);terrain.c.set(before.c||new Uint8Array(RES*RES*4));terrain.dirty()}if(editObject)editObject.position.copy(originalPosition)}
 else{history.push(before);if(history.length>10)history.shift();future.length=0;updateHistory()}
 terrain.end();down=false;lastPoint=null;moveOffset=null;editObject=null;originalPosition=null;syncFields();changed();
}
renderer.domElement.addEventListener('pointerdown',e=>{if(e.button!==0)return;const action=intent.down(e);if(action==='navigate'){finishEdit(true);ring.visible=false;return}startEvent={clientX:e.clientX,clientY:e.clientY};},true);
renderer.domElement.addEventListener('pointermove',e=>{const action=intent.move(e);if(action==='navigate'){ring.visible=false;return}if(mode==='paint'){const h=hit(e);if(h)brushAt(h.point);else ring.visible=false}
 if(action!=='drag')return;if(!down&&startEvent&&(mode==='paint'||mode==='move'))beginEdit(startEvent);
 if(down){let h=hit(e);if(h){if(mode==='paint')strokeTo(h.point);else if(editObject){editObject.position.copy(h.point).add(moveOffset);syncFields()}}}
});
function releasePointer(e,cancel=false){const result=intent.up(e,cancel);if(result==='cancel')finishEdit(true);else if(down)finishEdit();else if(result==='tap'){
 const ground=hit(e);if(mode==='place'&&ground){checkpoint();const seed=(nextId*1747+Date.now())%100000;const o=addObject(activeType,ground.point.x,ground.point.z,seed);if(activeType==='gavilan')o.position.y+=3;select(o);changed();toast(SPECIES[activeType].name+' colocado')}
 else if(mode==='paint'&&ground){beginEdit(e);finishEdit()}
 else select(owner(hit(e,objects)));
 }if(!intent.pointers.size)startEvent=null;
}
renderer.domElement.addEventListener('pointerup',e=>releasePointer(e),true);
renderer.domElement.addEventListener('pointercancel',e=>releasePointer(e,true),true);
renderer.domElement.addEventListener('lostpointercapture',e=>{if(intent.pointers.has(e.pointerId))releasePointer(e,true)});
renderer.domElement.addEventListener('pointerleave',()=>{if(!down)ring.visible=false});
window.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(document.activeElement.tagName))return;if(e.key==='Escape'){finishEdit(true);intent.reset();closeDrawers();setMode('orbit')}if(down)return;if(e.key==='Delete')$('#delete').click();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}});
function closeDrawers(){document.body.classList.remove('catalog-open','object-open');$('#mobileCatalog').setAttribute('aria-expanded','false');$('#mobileObject').setAttribute('aria-expanded','false')}
$('#mobileCatalog').onclick=()=>{const open=!document.body.classList.contains('catalog-open');closeDrawers();document.body.classList.toggle('catalog-open',open);$('#mobileCatalog').setAttribute('aria-expanded',String(open))};
$('#mobileObject').onclick=()=>{const open=!document.body.classList.contains('object-open');closeDrawers();document.body.classList.toggle('object-open',open);$('#mobileObject').setAttribute('aria-expanded',String(open))};
$$('.drawer-close').forEach(b=>b.onclick=closeDrawers);
$('#focus').onclick=()=>{if(!selected)return;const b=new T.Box3().setFromObject(selected),c=b.getCenter(new T.Vector3()),size=b.getSize(new T.Vector3()),d=Math.max(1.3,size.length()*1.4);controls.target.copy(c);camera.position.copy(c).add(new T.Vector3(1,.7,1).normalize().multiplyScalar(d));controls.update();closeDrawers()};
$$('[data-file-action]').forEach(b=>b.onclick=()=>$('#'+b.dataset.fileAction).click());
$('#recover').onclick=async()=>{try{const db=await database();const s=await new Promise((resolve,reject)=>{const q=db.transaction('project').objectStore('project').get('backup-before-update-02');q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)});db.close();if(!validState(s)){toast('Todavía no hay un respaldo anterior disponible');return}checkpoint();restore(s);autosaveBlocked=false;changed();toast('Respaldo recuperado. Puedes deshacer esta acción.')}catch{toast('No se pudo leer el respaldo')}};
// The workshop only changes catalog entries. Map instances are separate.
let draft=null,previewScene=null,previewRenderer=null,previewControls=null,previewCamera=null,previewObject=null,previewFrame=null;
function closeStudio(){cancelAnimationFrame(previewFrame);previewControls?.dispose();if(previewObject)releaseInstance(previewObject);previewRenderer?.dispose();previewRenderer=null;$('#modulePreview').replaceChildren();$('#moduleDialog').close();draft=null}
function drawDraft(){if(!draft)return;draft.name=$('#moduleName').value.trim();draft.category=$('#moduleCategory').value;draft.height=Number($('#moduleHeight').value);draft.yaw=Number($('#moduleYaw').value);if(!Number.isFinite(draft.height)||draft.height<.05||draft.height>100)return;if(previewObject){previewScene.remove(previewObject);releaseInstance(previewObject)}previewObject=instance(draft);previewScene.add(previewObject);const b=new T.Box3().setFromObject(previewObject),c=b.getCenter(new T.Vector3()),d=Math.max(.3,b.getSize(new T.Vector3()).length()*1.3);previewCamera.near=Math.max(.001,d/1000);previewCamera.far=d*20;previewCamera.updateProjectionMatrix();previewCamera.position.copy(c).add(new T.Vector3(1,.7,1).normalize().multiplyScalar(d));previewControls.target.copy(c);previewControls.update()}
function openStudio(item){draft=item;$('#moduleName').value=item.name;$('#moduleCategory').value=item.category;$('#moduleHeight').value=item.height.toFixed(2);$('#moduleYaw').value=item.yaw||0;$('#moduleError').textContent='';$('#moduleDialog').showModal();previewRenderer=new T.WebGLRenderer({antialias:true});previewRenderer.setPixelRatio(Math.min(devicePixelRatio,1.5));previewRenderer.setSize(Math.max(250,$('#modulePreview').clientWidth),280);previewRenderer.outputColorSpace=T.SRGBColorSpace;$('#modulePreview').append(previewRenderer.domElement);previewScene=new T.Scene();previewScene.background=new T.Color('#e7e2d2');previewScene.add(new T.HemisphereLight('#fff6df','#75674e',2));const light=new T.DirectionalLight('#fff4de',3);light.position.set(3,7,4);previewScene.add(light);previewCamera=new T.PerspectiveCamera(38,previewRenderer.domElement.width/previewRenderer.domElement.height,.01,10000);previewControls=new OrbitControls(previewCamera,previewRenderer.domElement);previewObject=null;drawDraft();function loop(){previewFrame=requestAnimationFrame(loop);previewControls.update();previewRenderer.render(previewScene,previewCamera)}loop()}
$('#newModule').onclick=()=>$('#moduleFile').click();$('#moduleFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;$('#newModule').disabled=true;try{let item;if(file.name.toLowerCase().endsWith('.mlmod')){if(file.size>115*1024*1024)throw Error('Paquete demasiado grande');item=await fromPackage(JSON.parse(await file.text()))}else{if(file.size>80*1024*1024)throw Error('Usa un GLB de hasta 80 MB');item=await prepare(await file.arrayBuffer(),{name:file.name.replace(/\.glb$/i,'').slice(0,80),category:'buildings',height:3,yaw:0})}if(getModule(item.id)?.template){toast('Este modelo ya existe en el catálogo. Puedes recuperarlo si lo retiraste.');return}openStudio(item)}catch(err){toast(err.message)}finally{e.target.value='';$('#newModule').disabled=false}};
for(const id of ['moduleName','moduleCategory','moduleHeight','moduleYaw'])$('#'+id).oninput=drawDraft;
$('#cancelModule').onclick=closeStudio;$('#moduleDialog').addEventListener('cancel',e=>{e.preventDefault();closeStudio()});
$('#acceptModule').onclick=async()=>{if(!draft)return;$('#acceptModule').disabled=true;try{drawDraft();await register(draft);syncModuleSpecies();renderModules();closeStudio();toast('Módulo añadido al catálogo de este navegador')}catch(e){$('#moduleError').textContent=e.message}finally{$('#acceptModule').disabled=false}};
function renderModules(){const container=$('#moduleCards');container.replaceChildren();const filter=$('#moduleFilter').value,showHidden=$('#showHidden').checked;let count=0;for(const m of allModules()){if(m.missing||(m.hidden||m.retired)&&!showHidden||filter!=='all'&&m.category!==filter)continue;count++;const wrap=document.createElement('div');wrap.className='module-entry';container.append(wrap);card(wrap,m.name,CATEGORIES[m.category]+' · '+(m.source==='shared'?'Compartido':'Local'),thumbnail(m.id),()=>{if(m.hidden||m.retired)return;activeType=m.id;setMode('place');closeDrawers()});const actions=document.createElement('div');actions.className='module-actions';const exp=document.createElement('button');exp.textContent='Exportar módulo';exp.onclick=()=>{try{downloadJSON(modulePackage(m),m.id.slice(4)+'.mlmod');toast('Paquete listo para la carpeta de módulos compartidos')}catch(e){toast(e.message)}};const del=document.createElement('button');del.textContent=m.retired?'Retirado en publicación':m.hidden?'Recuperar':'Retirar';del.disabled=!!m.retired;del.title='Mantiene las copias colocadas en el mapa';del.onclick=async()=>{try{await hideModule(m,!m.hidden);if(activeType===m.id)setMode('select');renderModules();toast(m.hidden?'Ficha retirada; los elementos del mapa se conservan':'Ficha recuperada')}catch{toast('No se pudo guardar el cambio del catálogo')}};actions.append(exp,del);wrap.append(actions)}$('#moduleEmpty').hidden=count>0}
$('#moduleFilter').onchange=renderModules;$('#showHidden').onchange=renderModules;renderModules();
function resize(){let w=vp.clientWidth,h=vp.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(vp);resize();
let frame=0;function animate(){requestAnimationFrame(animate);controls.update();if(camera.position.x>=X0&&camera.position.x<=X1&&camera.position.z>=Z0&&camera.position.z<=Z1){const floor=heightAt(camera.position.x,camera.position.z)+1.15;if(camera.position.y<floor)camera.position.y=floor}const now=performance.now()/1000;animateWater(now);animateProps(objects,now);if(selected){boxHelper.update();axes.position.copy(selected.position)}if(showLabels&&frame++%3===0){for(const [o,el]of labels){if(o.userData.type.startsWith('piedra')){el.hidden=true;continue}const p=o.position.clone();p.y+=SPECIES[o.userData.type].height*o.scale.x+.45;p.project(camera);el.hidden=p.z>1||p.z< -1||Math.abs(p.x)>1||Math.abs(p.y)>1;if(!el.hidden){el.style.left=(p.x*.5+.5)*vp.clientWidth+'px';el.style.top=(-p.y*.5+.5)*vp.clientHeight+'px'}}}renderer.render(scene,camera)}
await load();list();select(null);updateBrush();updateHistory();$('#loading').hidden=true;setMode('orbit');animate();if(moduleWarnings.length)toast(moduleWarnings.join(' · '));
