import * as T from 'three';
export const SPECIES={maguey:{name:'Maguey',note:'Hojas rígidas · azul agave',height:2.2},majagua:{name:'Majagua',note:'Copa densa · hoja ancha',height:6.6},vid:{name:'Vid',note:'Tronco bajo · hoja lobulada',height:1.9},eucalipto:{name:'Eucalipto',note:'Alto · follaje colgante',height:12.7},jacaranda:{name:'Jacaranda',note:'Copa abierta · flor violeta',height:8.0},dolar:{name:'Eucalipto dólar',note:'Hoja redonda · verde plata',height:5.2},lavanda:{name:'Lavanda arbusto',note:'Flor violeta · mata aromática',height:1.05},washingtonia:{name:'Palma washingtonia',note:'Tronco robusto · corona de abanicos',height:5.4},cactus:{name:'Cactus columnar',note:'Brazos verticales · verde gris',height:3.4},cirio:{name:'Cirio',note:'Silueta alta · ramificación escasa',height:7.2},formio:{name:'Formio',note:'Hojas largas · mata en abanico',height:1.7},nopal:{name:'Nopal',note:'Pencas carnosas · verde mate',height:2.4},silverDoll:{name:'Silver doll',note:'Follaje plateado · arbusto compacto',height:1.25},arbusto:{name:'Arbusto común',note:'Verde mixto · copa irregular',height:1.45},piedraS:{name:'Piedra pequeña',note:'0,25–0,50 m',height:.38},piedraM:{name:'Roca mediana',note:'0,70–1,20 m',height:.85},piedraL:{name:'Roca grande',note:'1,50–2,50 m',height:1.7}};
export function random(seed=1){let s=seed>>>0;return ()=>{s+=0x6D2B79F5;let t=s;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return ((t^t>>>14)>>>0)/4294967296}}
const color=new T.Color(),dummy=new T.Object3D();
function merge(parts){let ps=[],ns=[],uvs=[];for(let {g,m} of parts){g=g.index?g.toNonIndexed():g.clone();g.applyMatrix4(m);ps.push(...g.attributes.position.array);ns.push(...g.attributes.normal.array);if(g.attributes.uv)uvs.push(...g.attributes.uv.array);g.dispose()}let g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(ps,3));g.setAttribute('normal',new T.Float32BufferAttribute(ns,3));if(uvs.length===ps.length/3*2)g.setAttribute('uv',new T.Float32BufferAttribute(uvs,2));return g}
function segment(parts,a,b,r1,r2){a=new T.Vector3(...a);b=new T.Vector3(...b);const d=b.clone().sub(a),q=new T.Quaternion().setFromUnitVectors(new T.Vector3(0,1,0),d.clone().normalize());parts.push({g:new T.CylinderGeometry(r2,r1,d.length(),7,1),m:new T.Matrix4().compose(a.add(b).multiplyScalar(.5),q,new T.Vector3(1,1,1))})}
function leafShape(type){const p=[],uv=[],idx=[],steps=16; p.push(0,0,.035);uv.push(.5,.5);for(let i=0;i<=steps;i++){let a=i/steps*Math.PI*2,x=Math.sin(a)*.5,y=Math.cos(a)*.5;if(type==='heart'){x*=1+.28*Math.cos(a);y-=.13*Math.max(0,Math.cos(a))**8}else if(type==='grape'){const lobes=1+.23*Math.cos(a*5);x*=lobes;y*=lobes}else if(type==='long'){x*=.27; y*=1.2}p.push(x,y,.04*(1-Math.abs(x)*2)-.05*Math.abs(y));uv.push(x+.5,y+.5);if(i<steps)idx.push(0,i+1,i+2)}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(p,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.setIndex(idx);g.computeVertexNormals();return g}
const leafTex=(()=>{let c=document.createElement('canvas');c.width=c.height=128;let x=c.getContext('2d'),g=x.createLinearGradient(0,0,128,100);g.addColorStop(0,'#f5f4dd');g.addColorStop(.5,'#d8dfbf');g.addColorStop(1,'#b6c397');x.fillStyle=g;x.fillRect(0,0,128,128);x.strokeStyle='#d8e0b4';x.lineWidth=1.4;x.beginPath();x.moveTo(64,0);x.lineTo(64,128);x.stroke();x.lineWidth=.65;for(let i=15;i<120;i+=15){x.beginPath();x.moveTo(64,i);x.lineTo(6,i-21);x.moveTo(64,i);x.lineTo(122,i-21);x.stroke()}let t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;return t})();
const barkTex=(()=>{let c=document.createElement('canvas');c.width=128;c.height=256;let x=c.getContext('2d'),r=random(244);x.fillStyle='#a2997f';x.fillRect(0,0,128,256);for(let i=0;i<450;i++){x.strokeStyle=i%3?'#756f5c':'#c2b69a';x.globalAlpha=.3+r()*.3;x.lineWidth=.3+r()*2;x.beginPath();let xx=r()*128,yy=r()*256;x.moveTo(xx,yy);x.bezierCurveTo(xx+4,yy+14,xx-3,yy+32,xx+r()*6,yy+60);x.stroke()}let t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;t.wrapS=t.wrapT=T.RepeatWrapping;return t})();
const bark=new T.MeshStandardMaterial({map:barkTex,color:'#8c7b58',roughness:1});const paleBark=new T.MeshStandardMaterial({map:barkTex,color:'#c6c0a3',roughness:1});
function leaves(group,positions,type,palette,r,size){let geo=leafShape(type),mat=new T.MeshStandardMaterial({map:leafTex,color:'#ffffff',roughness:.88,side:T.DoubleSide});let mesh=new T.InstancedMesh(geo,mat,positions.length);positions.forEach((p,i)=>{dummy.position.set(...p);dummy.rotation.set((r()-.5)*2.9,r()*Math.PI*2,r()*6);let s=size*(.65+r()*.6);dummy.scale.set(s,s,1);dummy.updateMatrix();mesh.setMatrixAt(i,dummy.matrix);color.set(palette[Math.floor(r()*palette.length)]);mesh.setColorAt(i,color)});mesh.castShadow=true;mesh.receiveShadow=true;mesh.instanceMatrix.needsUpdate=true;mesh.computeBoundingSphere();group.add(mesh)}
function cluster(out,center,rx,ry,rz,n,r){for(let i=0;i<n;i++){let theta=r()*Math.PI*2,u=r()*2-1,rr=Math.cbrt(r()),k=Math.sqrt(1-u*u);out.push([center[0]+Math.cos(theta)*k*rr*rx,center[1]+u*rr*ry,center[2]+Math.sin(theta)*k*rr*rz])}}
function agave(r){let group=new T.Group(),parts=[];for(let layer=0;layer<3;layer++){let num=layer===0?13:layer===1?10:7;for(let i=0;i<num;i++){let angle=i/num*Math.PI*2+layer*.38,length=1.8+r()*.7,spread=[1.75,1.15,.48][layer],height=[.8,1.55,2.1][layer],w=[.26,.23,.18][layer],p=[],uv=[],idx=[];for(let k=0;k<=9;k++){let t=k/9,width=w*Math.sin(Math.PI*Math.pow(t,.6))+.012*(1-t),rad=.07+spread*t,yy=.05+height*t-.18*Math.sin(t*Math.PI);for(let s of [-1,0,1]){p.push(Math.cos(angle)*rad+Math.sin(angle)*width*s,yy+(s===0?.10*Math.sin(Math.PI*t):0),Math.sin(angle)*rad-Math.cos(angle)*width*s);uv.push((s+1)/2,t)}}for(let k=0;k<9;k++)for(let s=0;s<2;s++){let a=k*3+s,b=a+3;idx.push(a,b,a+1,a+1,b,b+1)}let g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(p,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.setIndex(idx);g.computeVertexNormals();let mesh=new T.Mesh(g,new T.MeshStandardMaterial({color:['#77958c','#617f73','#8ba49a'][layer],roughness:.74,side:T.DoubleSide}));mesh.castShadow=mesh.receiveShadow=true;group.add(mesh); // brown terminal spine
let tip=[Math.cos(angle)*(.07+spread),.05+height,Math.sin(angle)*(.07+spread)];segment(parts,tip,[tip[0]*1.02,tip[1]+.09,tip[2]*1.02],.012,0)}}group.add(new T.Mesh(merge(parts),new T.MeshStandardMaterial({color:'#393e2a'})));return group}
function rock(type,r){let g=new T.IcosahedronGeometry(1,2),p=g.attributes.position;for(let i=0;i<p.count;i++){let x=p.getX(i),y=p.getY(i),z=p.getZ(i),f=1+.11*Math.sin(x*8+z*3)+.06*Math.sin(y*13-x*4);p.setXYZ(i,x*f,Math.max(-.36,y*f*.65),z*f*.8)}g.computeVertexNormals();const scales={piedraS:.31,piedraM:.73,piedraL:1.4};g.scale(scales[type],scales[type],scales[type]);g.translate(0,scales[type]*.36,0);let cs=[];for(let i=0;i<p.count;i++){let f=(Math.sin(p.getX(i)*47+p.getY(i)*34)*.5+.5);color.set('#aaa28a').lerp(new T.Color('#6b7065'),f*.65);cs.push(color.r,color.g,color.b)}g.setAttribute('color',new T.Float32BufferAttribute(cs,3));let group=new T.Group(),m=new T.Mesh(g,new T.MeshStandardMaterial({vertexColors:true,roughness:1}));m.castShadow=m.receiveShadow=true;group.add(m);group.rotation.y=r()*6;return group}
function palmFan(c){const p=[0,0,0],idx=[];for(let i=0;i<=16;i++){let a=.12+i/16*(Math.PI-.24),radius=1.25*(.92+.08*Math.sin(i*2.3));p.push(Math.cos(a)*radius,.48+Math.sin(a)*radius,.035*Math.sin(i));if(i<16)idx.push(0,i+1,i+2)}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(p,3));geo.setIndex(idx);geo.computeVertexNormals();const m=new T.Mesh(geo,new T.MeshStandardMaterial({color:c,side:T.DoubleSide,roughness:.82}));m.castShadow=true;return m}
function washingtonia(r){const g=new T.Group(),parts=[];segment(parts,[0,0,0],[.04,3.35,.02],.5,.27);const trunk=new T.Mesh(merge(parts),bark);trunk.castShadow=trunk.receiveShadow=true;g.add(trunk);for(let i=0;i<12;i++){const a=i/12*Math.PI*2;let old=meshLeaf(i%2?'#765d36':'#8a7045');old.position.set(Math.cos(a)*.18,3.08-i*.025,Math.sin(a)*.18);old.rotation.set(.55,a,0);old.scale.set(.22,.92,1);g.add(old)}const green=['#35733c','#4f8a48','#69a153'];for(let i=0;i<15;i++){const a=i/15*Math.PI*2+(r()-.5)*.1,fan=palmFan(green[i%3]);fan.position.set(0,3.35,0);fan.rotation.set(-.12+(i%3-.8)*.18,a,0);fan.scale.setScalar(.92+r()*.18);g.add(fan)}return g}
function desertPlant(type,r){const g=new T.Group(),mat=new T.MeshStandardMaterial({color:type==='nopal'?'#568452':'#64825c',roughness:.92});if(type==='cactus'){const stems=[[0,0,0,3.2,.28],[.28,.65,0,1.45,.17],[-.25,1.15,.04,1.05,.15]];for(const [x,y,z,h,w]of stems){let m=new T.Mesh(new T.CapsuleGeometry(w,h-w*2,8,10),mat);m.position.set(x,y+h/2,z);m.castShadow=true;g.add(m)}return g}if(type==='cirio'){let trunk=new T.Mesh(new T.ConeGeometry(.28,.11,7,26),mat);trunk.geometry.scale(1,65,1);trunk.position.y=3.55;trunk.castShadow=true;g.add(trunk);for(let i=0;i<18;i++){let y=.7+r()*5.7,a=r()*6.28,twig=meshLeaf('#718c55');twig.position.set(Math.cos(a)*.12,y,Math.sin(a)*.12);twig.rotation.set(r()*2,a,r()*2);twig.scale.set(.12,.42,1);g.add(twig)}return g}if(type==='formio'){for(let i=0;i<28;i++){let a=(r()-.5)*1.15+(i%2?0:Math.PI),leaf=meshLeaf(i%4===0?'#8f493d':'#596d3b');leaf.position.set((r()-.5)*.3,.05,(r()-.5)*.26);leaf.rotation.set(0,a,(r()-.5)*.22);leaf.scale.set(.18,1.25+r()*.55,1);leaf.translateY(.65);g.add(leaf)}return g}if(type==='nopal'){const pads=[[0,.62,0,.62,.9,0],[0,1.42,0,.55,.78,.08],[-.48,1.45,.02,.43,.62,-.42],[.46,1.7,.02,.4,.58,.38],[-.7,2.02,.02,.34,.48,-.2]];for(const [x,y,z,w,h,rz]of pads){let p=new T.Mesh(new T.SphereGeometry(1,12,9),mat);p.position.set(x,y,z);p.scale.set(w,h,.11);p.rotation.z=rz;p.castShadow=true;g.add(p)}return g}return g}
function smallPlant(type,r){let g=new T.Group();let colors=type==='lavanda'?['#78608f','#9072a7','#667846']:type==='silverDoll'?['#aab9aa','#c0cbbb','#82988d']:['#41683c','#5c7d49','#78925c'];for(let i=0;i<(type==='lavanda'?42:24);i++){let a=r()*6.283,rad=Math.sqrt(r())*(type==='lavanda'?.72:.8),h=.35+r()*(type==='lavanda'?.65:.85);let stem=new T.Mesh(new T.CylinderGeometry(.012,.018,h,5),new T.MeshStandardMaterial({color:'#596544',roughness:1}));stem.position.set(Math.cos(a)*rad,h/2,Math.sin(a)*rad);stem.rotation.z=(r()-.5)*.18;g.add(stem);let crown=new T.Mesh(new T.IcosahedronGeometry(1,1),new T.MeshStandardMaterial({color:colors[i%colors.length],roughness:.9,flatShading:true}));crown.position.set(stem.position.x,h+.06,stem.position.z);crown.scale.set(type==='lavanda'?.08:.22,type==='lavanda'?.18:.25,type==='lavanda'?.08:.2);crown.castShadow=true;g.add(crown)}return g}
function meshLeaf(c){const m=new T.Mesh(leafShape('long'),new T.MeshStandardMaterial({color:c,side:T.DoubleSide,roughness:.85}));m.castShadow=true;return m}
export function createPlant(type,seed=12){const r=random(seed);if(type==='maguey')return agave(r);if(type==='washingtonia')return washingtonia(r);if(['cactus','cirio','formio','nopal'].includes(type))return desertPlant(type,r);if(type.startsWith('piedra'))return rock(type,r);if(['lavanda','silverDoll','arbusto'].includes(type))return smallPlant(type,r);const group=new T.Group(),parts=[],positions=[],flowers=[];const heights={majagua:6.0,vid:1.7,eucalipto:12,jacaranda:7,dolar:4.6};let h=heights[type]||5;
// Each species has its own branching, crown distribution and leaf silhouette.
if(type==='vid'){
segment(parts,[0,0,0],[.08,.65,.03],.15,.10);for(let k=0;k<5;k++){let a=k*2.4,end=[Math.cos(a)*.58,1.25+r()*.35,Math.sin(a)*.48];segment(parts,[.08,.5,.03],end,.055,.018);cluster(positions,end,.65,.48,.5,110,r)}leaves(group,positions,'grape',['#5f7d32','#809742','#45642f','#96a858'],r,.32);
let berries=[];for(let k=0;k<5;k++){let a=k*2.4;for(let b=0;b<13;b++)berries.push([Math.cos(a)*.5+(r()-.5)*.12,.85+r()*.24,Math.sin(a)*.45+(r()-.5)*.12])}let bg=new T.SphereGeometry(.043,5,4),bm=new T.InstancedMesh(bg,new T.MeshStandardMaterial({color:'#646941',roughness:.7}),berries.length);berries.forEach((p,i)=>{dummy.position.set(...p);dummy.scale.setScalar(1);dummy.rotation.set(0,0,0);dummy.updateMatrix();bm.setMatrixAt(i,dummy.matrix)});group.add(bm);
}else{
let trunkTop=type==='eucalipto'?h*.74:h*.57;segment(parts,[0,0,0],[.12,trunkTop*.48,.02],h*.036,h*.022);segment(parts,[.12,trunkTop*.48,.02],[-.12,trunkTop,.1],h*.022,h*.01);
let count={majagua:15,eucalipto:20,jacaranda:15,dolar:14}[type];for(let k=0;k<count;k++){let angle=k*2.399+r()*.45,level=k/count,reach,yy,spread;
if(type==='majagua'){reach=1.55+Math.sin(level*Math.PI)*.7;yy=2.7+level*2.6;spread=[1.15,1.15,1.15]}
if(type==='eucalipto'){reach=(1-level)*2.4+.7;yy=4.2+level*7.8;spread=[1.2,.95,1.1]}
if(type==='jacaranda'){reach=1.8+Math.sin(level*Math.PI)*1.2;yy=3.8+level*2.3;spread=[1.35,.7,1.25]}
if(type==='dolar'){reach=1.1+Math.sin(level*Math.PI)*1.1;yy=2.0+level*2.5;spread=[.9,.85,.9]}
let start=[.06,Math.min(yy*.64,trunkTop),0],mid=[Math.cos(angle)*reach*.55,yy-.35,Math.sin(angle)*reach*.55],end=[Math.cos(angle)*reach,yy,Math.sin(angle)*reach];segment(parts,start,mid,h*.012,.04);segment(parts,mid,end,.04,.014);for(let b=0;b<3;b++){let ba=angle+(b-1)*.7;segment(parts,mid,[end[0]+Math.cos(ba)*.45,yy+.35,end[2]+Math.sin(ba)*.45],.021,.005)}cluster(positions,end,...spread,type==='jacaranda'?85:130,r);if(type==='jacaranda')cluster(flowers,[end[0],yy+.1,end[2]],...spread,95,r);
}
let top=[0,type==='eucalipto'?12: h-.1,0];cluster(positions,top,type==='eucalipto'?.75:1.1,.7,1,180,r);
if(type==='majagua')leaves(group,positions,'heart',['#4f703e','#698253','#3f653e','#78916a'],r,.52);
if(type==='eucalipto')leaves(group,positions,'long',['#697d67','#7f927b','#536c57','#93a38e'],r,.73);
if(type==='dolar')leaves(group,positions,'round',['#85a49b','#729389','#a3bcb0','#64867b'],r,.32);
if(type==='jacaranda'){leaves(group,positions,'long',['#637d47','#729255','#466340'],r,.35);leaves(group,flowers,'round',['#9678b6','#b79bcc','#8662ac','#c1a6db'],r,.23)}
}
let trunk=new T.Mesh(merge(parts),type==='eucalipto'||type==='dolar'?paleBark:bark);trunk.castShadow=trunk.receiveShadow=true;group.add(trunk);return group}
export function disposePlant(group){group.traverse(o=>{if(o.isMesh){o.geometry.dispose();if(o.material!==bark&&o.material!==paleBark)o.material.dispose();if(o.isInstancedMesh)o.dispose()}})}
