import * as T from 'three';import {random} from './flora.js';import {HEIGHT_GRID} from './inegi-data.js';
export const X0=HEIGHT_GRID.x0,X1=HEIGHT_GRID.x1,Z0=HEIGHT_GRID.z0,Z1=HEIGHT_GRID.z1;
export const WIDTH=X1-X0,DEPTH=Z1-Z0,CENTER_X=(X0+X1)/2,CENTER_Z=(Z0+Z1)/2,RES=1024;
export const SOILS=[{name:'Pradera',note:'Verdes · hierba irregular',a:[78,91,43],b:[131,137,71]},{name:'Pasto seco',note:'Ocre · vegetación baja',a:[122,111,64],b:[173,159,99]},{name:'Tierra de sendero',note:'Barro · suelo compactado',a:[119,90,59],b:[175,143,103]},{name:'Grava natural',note:'Piedra fina · tono arena',a:[131,126,109],b:[191,179,149]},{name:'Suelo pedregoso',note:'Roca · material mineral',a:[104,110,100],b:[162,157,133]},{name:'Piso de bosque',note:'Hojarasca · tierra oscura',a:[67,72,39],b:[120,113,64]},{name:'Agua',note:'Azul natural · para dibujar arroyos',a:[43,103,119],b:[91,155,164]},{name:'Arena',note:'Arena clara · grano fino',a:[166,143,101],b:[220,203,158]},{name:'Tierra con grava',note:'Suelo mixto · piedra dispersa',a:[105,91,71],b:[163,146,115]},{name:'Agua azul profundo',note:'Azul oscuro · cauces y profundidad',a:[22,65,91],b:[48,119,143]},{name:'Camino de tierra',note:'Tierra firme · huellas suaves',a:[112,76,49],b:[169,126,83]},{name:'Pasto con hojas',note:'Verde natural · hojas dispersas',a:[55,77,38],b:[112,125,67]}];
function noise(x,y,s){let z=Math.sin(x*127.1+y*311.7+s*74.7)*43758.5453;return z-Math.floor(z)}
function smooth(x,y,s){let ix=Math.floor(x),iy=Math.floor(y),fx=x-ix,fy=y-iy;fx=fx*fx*(3-2*fx);fy=fy*fy*(3-2*fy);let a=noise(ix,iy,s),b=noise(ix+1,iy,s),c=noise(ix,iy+1,s),d=noise(ix+1,iy+1,s);return (a*(1-fx)+b*fx)*(1-fy)+(c*(1-fx)+d*fx)*fy}
export function soilTexture(id){const c=document.createElement('canvas');c.width=c.height=512;const ctx=c.getContext('2d'),im=ctx.createImageData(512,512),r=random(499+id),s=SOILS[id];for(let y=0;y<512;y++)for(let x=0;x<512;x++){ // periodic multi-scale field, matching opposite tile boundaries
let f=0,amp=.52;for(let k=0;k<4;k++){let freq=2**(k+1),xx=x/512*freq,yy=y/512*freq;let ix=Math.floor(xx),iy=Math.floor(yy),fx=xx-ix,fy=yy-iy;fx=fx*fx*(3-2*fx);fy=fy*fy*(3-2*fy);const n=(a,b)=>noise((a+freq)%freq,(b+freq)%freq,id+k);f+=amp*((n(ix,iy)*(1-fx)+n(ix+1,iy)*fx)*(1-fy)+(n(ix,iy+1)*(1-fx)+n(ix+1,iy+1)*fx)*fy);amp*=.5}f=Math.min(1,Math.max(0,f+(r()-.5)*.18));let p=(y*512+x)*4;for(let k=0;k<3;k++)im.data[p+k]=s.a[k]+(s.b[k]-s.a[k])*f;im.data[p+3]=255}ctx.putImageData(im,0,0);
// Wrap small surface details through tile boundaries.
for(let i=0;i<(id===3?4200:id===4?1800:9000);i++){let x=r()*512,y=r()*512,v=r(),rr=(id===4?1.5: id===3?.55:.8)+r()*(id===4?5:id===3?2.1:3.5);ctx.fillStyle=`rgba(${s.b[0]+15},${s.b[1]+12},${s.b[2]+5},${.18+r()*.35})`;ctx.strokeStyle=`rgba(${s.a[0]-15},${s.a[1]-10},${s.a[2]-8},.27)`;ctx.lineWidth=.5;for(let dx of [-512,0,512])for(let dy of [-512,0,512]){if(x+dx+rr<0||x+dx-rr>512||y+dy+rr<0||y+dy-rr>512)continue;ctx.beginPath();ctx.ellipse(x+dx,y+dy,rr,rr*(id<2?.22:.65),r()*3,0,6.283);ctx.fill();if(id>=3)ctx.stroke()}}
let tex=new T.CanvasTexture(c);tex.wrapS=tex.wrapT=T.RepeatWrapping;tex.colorSpace=T.SRGBColorSpace;tex.anisotropy=8;return {tex,canvas:c}}
const ELEV_BASE=Math.min(...HEIGHT_GRID.elev);
export function heightAt(x,z){const g=HEIGHT_GRID,fx=(x-g.x0)/(g.x1-g.x0)*(g.NX-1),fz=(z-g.z0)/(g.z1-g.z0)*(g.NZ-1),ix=Math.min(Math.max(Math.floor(fx),0),g.NX-2),iz=Math.min(Math.max(Math.floor(fz),0),g.NZ-2),tx=Math.min(Math.max(fx-ix,0),1),tz=Math.min(Math.max(fz-iz,0),1),e00=g.elev[iz*g.NX+ix],e10=g.elev[iz*g.NX+ix+1],e01=g.elev[(iz+1)*g.NX+ix],e11=g.elev[(iz+1)*g.NX+ix+1];return (e00*(1-tx)+e10*tx)*(1-tz)+(e01*(1-tx)+e11*tx)*tz-ELEV_BASE}
export class Terrain {
 constructor(){this.textures=SOILS.map((_,i)=>soilTexture(i));this.a=new Uint8Array(RES*RES*4);this.b=new Uint8Array(RES*RES*4);this.c=new Uint8Array(RES*RES*4);this.base=new Uint8Array(RES*RES*4);for(let y=0;y<RES;y++)for(let x=0;x<RES;x++){let i=(y*RES+x)*4,variation=smooth(x/RES*7,y/RES*7,77);this.a[i]=Math.round(155+variation*90);this.a[i+1]=255-this.a[i]}this.base.set(this.a);this.ta=new T.DataTexture(this.a,RES,RES);this.tb=new T.DataTexture(this.b,RES,RES);this.tc=new T.DataTexture(this.c,RES,RES);for(let t of [this.ta,this.tb,this.tc]){t.minFilter=t.magFilter=T.LinearFilter;t.needsUpdate=true;t.generateMipmaps=false}
let g=new T.PlaneGeometry(WIDTH,DEPTH,HEIGHT_GRID.NX-1,HEIGHT_GRID.NZ-1);g.rotateX(-Math.PI/2);g.translate(CENTER_X,0,CENTER_Z);let p=g.attributes.position;for(let i=0;i<p.count;i++)p.setY(i,heightAt(p.getX(i),p.getZ(i)));g.computeVertexNormals();const m=new T.MeshStandardMaterial({color:0xffffff,roughness:1});m.onBeforeCompile=sh=>{sh.uniforms.wa={value:this.ta};sh.uniforms.wb={value:this.tb};sh.uniforms.wc={value:this.tc};this.textures.forEach((t,i)=>sh.uniforms['soil'+i]={value:t.tex});sh.vertexShader='varying vec2 worldXZ;\n'+sh.vertexShader;sh.vertexShader=sh.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\n worldXZ = position.xz;');sh.fragmentShader='varying vec2 worldXZ;uniform sampler2D wa,wb,wc,soil0,soil1,soil2,soil3,soil4,soil5,soil6,soil7,soil8,soil9,soil10,soil11;\nvec3 texLayer(sampler2D t,vec2 uv){mat2 r1=mat2(.819,.574,-.574,.819);mat2 r2=mat2(.342,-.940,.940,.342);vec3 a=texture2D(t,uv).rgb;vec3 b=texture2D(t,r1*uv*.613+vec2(.173,.417)).rgb;vec3 c=texture2D(t,r2*uv*.277+vec2(.619,.091)).rgb;return a*.34+b*.38+c*.28;}\n'+sh.fragmentShader;sh.fragmentShader=sh.fragmentShader.replace('#include <map_fragment>',`vec2 wuv=vec2((worldXZ.x+${(-X0).toFixed(1)})/${WIDTH.toFixed(1)},(worldXZ.y+${(-Z0).toFixed(1)})/${DEPTH.toFixed(1)});vec4 a=texture2D(wa,wuv),b=texture2D(wb,wuv),c=texture2D(wc,wuv);float sumW=max(.001,a.r+a.g+a.b+a.a+b.r+b.g+b.b+b.a+c.r+c.g+c.b+c.a);vec2 u=worldXZ*.017;vec3 soil=(texLayer(soil0,u)*a.r+texLayer(soil1,u)*a.g+texLayer(soil2,u*.8)*a.b+texLayer(soil3,u*1.3)*a.a+texLayer(soil4,u)*b.r+texLayer(soil5,u)*b.g+texLayer(soil6,u*.45)*b.b+texLayer(soil7,u*.8)*b.a+texLayer(soil8,u*1.1)*c.r+texLayer(soil9,u*.4)*c.g+texLayer(soil10,u*.75)*c.b+texLayer(soil11,u)*c.a)/sumW;float macro=.94+.06*sin(worldXZ.x*.009+sin(worldXZ.y*.007))*sin(worldXZ.y*.011);diffuseColor.rgb*=soil*macro;`)};this.mesh=new T.Mesh(g,m);this.mesh.receiveShadow=true;this.mesh.name='Terrain';this.stroke=null;
 }
 dirty(){this.ta.needsUpdate=true;this.tb.needsUpdate=true;this.tc.needsUpdate=true}
 start(){this.stroke={a:this.a.slice(),b:this.b.slice(),c:this.c.slice(),coverage:new Float32Array(RES*RES)}}
 end(){this.stroke=null}
 paint(x,z,radius,blend,id){if(!this.stroke)this.start();const sx=RES/WIDTH,sz=RES/DEPTH,px=(x-X0)/WIDTH*RES,py=(z-Z0)/DEPTH*RES,rx=radius*sx,ry=radius*sz;for(let yy=Math.max(0,Math.floor(py-ry*1.06));yy<=Math.min(RES-1,Math.ceil(py+ry*1.06));yy++)for(let xx=Math.max(0,Math.floor(px-rx*1.06));xx<=Math.min(RES-1,Math.ceil(px+rx*1.06));xx++){const dist=Math.hypot((xx+.5-px)/rx,(yy+.5-py)/ry);const edge=1+.05*Math.sin(xx*.73+Math.sin(yy*.51))*Math.sin(yy*.84);let t=(dist-(1-blend))/(edge-(1-blend));let f=1-Math.min(1,Math.max(0,t));f=f*f*(3-2*f);let ci=yy*RES+xx;if(f<=this.stroke.coverage[ci])continue;this.stroke.coverage[ci]=f;let p=ci*4,weights=[];for(let k=0;k<12;k++){let src=k<4?this.stroke.a:k<8?this.stroke.b:this.stroke.c,old=src[p+k%4],target=id<0?(k<4?this.base[p+k]:0):(id===k?255:0);weights[k]=old*(1-f)+target*f}let sum=weights.reduce((a,b)=>a+b,0);for(let k=0;k<12;k++){let dest=k<4?this.a:k<8?this.b:this.c;dest[p+k%4]=Math.round(weights[k]/Math.max(sum,1)*255)}}this.dirty()}
 path(points,radius,blend,id){this.start();for(let k=1;k<points.length;k++){let a=points[k-1],b=points[k],steps=Math.ceil(Math.hypot(b[0]-a[0],b[1]-a[1])/(radius*.3));for(let i=0;i<=steps;i++)this.paint(a[0]+(b[0]-a[0])*i/steps,a[1]+(b[1]-a[1])*i/steps,radius,blend,id)}this.end()}
}
